### ISSUE TITLE
Decide on an appropriate name for this pipeline

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fastquorum#2]
Things to keep in mind when

1. We may choose to add a few downstream tools:
   - variant calling (e.g. variant calling with `VarDictJava`'s pileup mode)

Ideas:

- `fastqconsensus`
- `fastqtoconsensus`
- `consensuscalling`
- `quorum`
- `consensus`

**Comment by pditommaso** [comment]
`fastquorum`

**Comment by nh13** [comment]
> `fastquorum`

`bfastquorum` ([link](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0007767) for the uninitiated)

**Comment by ameynert** [comment]
`fastqconsensus`

**Comment by DCGenomics** [comment]
fgly

**Comment by nh13** [comment]
> fgly

har har

**Comment by nh13** [comment]
`fastquorum` it is

**Comment by pditommaso** [comment]
<img src="https://media3.giphy.com/media/JqDeI2yjpSRgdh35oe/giphy.gif"/>

**Comment by pditommaso** [comment]
You need an accelerated course on marketing messaging 😄
